import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'countryCode'
})
export class CountryCodePipe implements PipeTransform {

  static countries: { name: string; translation: string; code: string }[] = [
    { name: 'Afghanistan', translation: 'Afghanistan', code: 'af' },
    { name: 'Albania', translation: 'Albanie', code: 'al' },
    { name: 'Algeria', translation: 'Algérie', code: 'dz' },
    { name: 'Andorra', translation: 'Andorre', code: 'ad' },
    { name: 'Angola', translation: 'Angola', code: 'ao' },
    { name: 'Anguilla', translation: 'Anguilla', code: 'ai' },
    { name: 'Antigua', translation: 'Antigua', code: 'ag' },
    { name: 'Argentina', translation: 'Argentine', code: 'ar' },
    { name: 'Armenia', translation: 'Arménie', code: 'am' },
    { name: 'Aruba', translation: 'Aruba', code: 'aw' },
    { name: 'Australia', translation: 'Australie', code: 'au' },
    { name: 'Austria', translation: 'Autriche', code: 'at' },
    { name: 'Azerbaijan', translation: 'Azerbaïdjan', code: 'az' },
    { name: 'Bahrain', translation: 'Bahrein', code: 'bh' },
    { name: 'Bangladesh', translation: 'Bangladesh', code: 'bd' },
    { name: 'Barbados', translation: 'Barbade', code: 'bb' },
    { name: 'Belarus', translation: 'Biélorussie', code: 'by' },
    { name: 'Belgium', translation: 'Belgique', code: 'be' },
    { name: 'Belize', translation: 'Belize', code: 'bz' },
    { name: 'Benin', translation: 'Bénin', code: 'bj' },
    { name: 'Bermuda', translation: 'Bermudes', code: 'bm' },
    { name: 'Bhutan', translation: 'Bhoutan', code: 'bt' },
    { name: 'Bolivia', translation: 'Bolivie', code: 'bo' },
    { name: 'Bosnia', translation: 'Bosnie', code: 'ba' },
    { name: 'Botswana', translation: 'Botswana', code: 'bw' },
    { name: 'Brazil', translation: 'Brésil', code: 'br' },
    { name: 'Bulgaria', translation: 'Bulgarie', code: 'bg' },
    { name: 'Burkina Faso', translation: 'Burkina Faso', code: 'bf' },
    { name: 'Burma', translation: 'Birmanie', code: 'mm' },
    { name: 'Burundi', translation: 'Burundi', code: 'bi' },
    { name: 'Cambodia', translation: 'Cambodge', code: 'kh' },
    { name: 'Cameroon', translation: 'Cameroun', code: 'cm' },
    { name: 'Canada', translation: 'Canada', code: 'ca' },
    { name: 'Cape Verde', translation: 'Cap-Vert', code: 'cv' },
    { name: 'Central African Republic', translation: 'République centrafricaine', code: 'cf' },
    { name: 'Chad', translation: 'Tchad', code: 'td' },
    { name: 'Chile', translation: 'Chili', code: 'cl' },
    { name: 'China', translation: 'Chine', code: 'cn' },
    { name: 'Colombia', translation: 'Colombie', code: 'co' },
    { name: 'Comoros', translation: 'Comores', code: 'km' },
    { name: 'Congo', translation: 'Congo', code: 'cd' },
    { name: 'Congo Brazzaville', translation: 'Congo Brazzaville', code: 'cg' },
    { name: 'Costa Rica', translation: 'Costa Rica', code: 'cr' },
    { name: 'Cote Divoire', translation: 'Cote d\'Ivoire', code: 'ci' },
    { name: 'Croatia', translation: 'Croatie', code: 'hr' },
    { name: 'Cuba', translation: 'Cuba', code: 'cu' },
    { name: 'Cyprus', translation: 'Chypre', code: 'cy' },
    { name: 'Czech Republic', translation: 'République Tchèque', code: 'cz' },
    { name: 'Denmark', translation: 'Danemark', code: 'dk' },
    { name: 'Djibouti', translation: 'Djibouti', code: 'dj' },
    { name: 'Dominica', translation: 'Dominique', code: 'dm' },
    { name: 'Dominican Republic', translation: 'République Dominicaine', code: 'do' },
    { name: 'Ecuador', translation: 'Equateur', code: 'ec' },
    { name: 'Egypt', translation: 'Egypte', code: 'eg' },
    { name: 'El Salvador', translation: 'Salvador', code: 'sv' },
    { name: 'England', translation: 'Angleterre', code: 'gb' },
    { name: 'Equatorial Guinea', translation: 'Guinée Equatoriale', code: 'gq' },
    { name: 'Estonia', translation: 'Estonie', code: 'ee' },
    { name: 'Ethiopia', translation: 'Ethiopie', code: 'et' },
    { name: 'Fiji', translation: 'Fidji', code: 'fj' },
    { name: 'Finland', translation: 'Finlande', code: 'fi' },
    { name: 'France', translation: 'France', code: 'fr' },
    { name: 'Gabon', translation: 'Gabon', code: 'ga' },
    { name: 'Gambia', translation: 'Gambie', code: 'gm' },
    { name: 'Georgia', translation: 'Géorgie', code: 'ge' },
    { name: 'Germany', translation: 'Allemagne', code: 'de' },
    { name: 'Ghana', translation: 'Ghana', code: 'gh' },
    { name: 'Gibraltar', translation: 'Gibraltar', code: 'gi' },
    { name: 'Greece', translation: 'Grèce', code: 'gr' },
    { name: 'Greenland', translation: 'Groenland', code: 'gl' },
    { name: 'Grenada', translation: 'Grenade', code: 'gd' },
    { name: 'Guadeloupe', translation: 'Guadeloupe', code: 'gp' },
    { name: 'Guam', translation: 'Guam', code: 'gu' },
    { name: 'Guatemala', translation: 'Guatemala', code: 'gt' },
    { name: 'Guinea', translation: 'Guinée', code: 'gn' },
    { name: 'Guyana', translation: 'Guyane', code: 'gy' },
    { name: 'Haiti', translation: 'Haïti', code: 'ht' },
    { name: 'Honduras', translation: 'Honduras', code: 'hn' },
    { name: 'Hong Kong', translation: 'Hong Kong', code: 'hk' },
    { name: 'Hungary', translation: 'Hongrie', code: 'hu' },
    { name: 'Iceland', translation: 'Islande', code: 'is' },
    { name: 'India', translation: 'Inde', code: 'in' },
    { name: 'Indonesia', translation: 'Indonésie', code: 'id' },
    { name: 'Iran', translation: 'Iran', code: 'ir' },
    { name: 'Iraq', translation: 'Irak', code: 'iq' },
    { name: 'Ireland', translation: 'Irlande', code: 'ie' },
    { name: 'Israel', translation: 'Israël', code: 'il' },
    { name: 'Italy', translation: 'Italie', code: 'it' },
    { name: 'Jamaica', translation: 'Jamaïque', code: 'jm' },
    { name: 'Japan', translation: 'Japon', code: 'jp' },
    { name: 'Jordan', translation: 'Jordanie', code: 'jo' },
    { name: 'Kazakhstan', translation: 'Kazakhstan', code: 'kz' },
    { name: 'Kenya', translation: 'Kenya', code: 'ke' },
    { name: 'Kiribati', translation: 'Kiribati', code: 'ki' },
    { name: 'Kuwait', translation: 'Koweit', code: 'kw' },
    { name: 'Kyrgyzstan', translation: 'Kirghizistan', code: 'kg' },
    { name: 'Laos', translation: 'Laos', code: 'la' },
    { name: 'Latvia', translation: 'Lettonie', code: 'lv' },
    { name: 'Lebanon', translation: 'Liban', code: 'lb' },
    { name: 'Lesotho', translation: 'Lesotho', code: 'ls' },
    { name: 'Liberia', translation: 'Libéria', code: 'lr' },
    { name: 'Libya', translation: 'Libye', code: 'ly' },
    { name: 'Liechtenstein', translation: 'Liechtenstein', code: 'li' },
    { name: 'Lithuania', translation: 'Lituanie', code: 'lt' },
    { name: 'Luxembourg', translation: 'Luxembourg', code: 'lu' },
    { name: 'Macau', translation: 'Macao', code: 'mo' },
    { name: 'Macedonia', translation: 'Macédoine', code: 'mk' },
    { name: 'Madagascar', translation: 'Madagascar', code: 'mg' },
    { name: 'Malawi', translation: 'Malawi', code: 'mw' },
    { name: 'Malaysia', translation: 'Malaisie', code: 'my' },
    { name: 'Maldives', translation: 'Maldives', code: 'mv' },
    { name: 'Mali', translation: 'Mali', code: 'ml' },
    { name: 'Malta', translation: 'Malte', code: 'mt' },
    { name: 'Martinique', translation: 'Martinique', code: 'mq' },
    { name: 'Mauritania', translation: 'Mauritanie', code: 'mr' },
    { name: 'Mauritius', translation: 'Ile Maurice', code: 'mu' },
    { name: 'Mayotte', translation: 'Mayotte', code: 'yt' },
    { name: 'Mexico', translation: 'Mexique', code: 'mx' },
    { name: 'Micronesia', translation: 'Micronésie', code: 'fm' },
    { name: 'Moldova', translation: 'Moldavie', code: 'md' },
    { name: 'Monaco', translation: 'Monaco', code: 'mc' },
    { name: 'Mongolia', translation: 'Mongolie', code: 'mn' },
    { name: 'Montenegro', translation: 'Monténégro', code: 'me' },
    { name: 'Montserrat', translation: 'Montserrat', code: 'ms' },
    { name: 'Morocco', translation: 'Maroc', code: 'ma' },
    { name: 'Mozambique', translation: 'Mozambique', code: 'mz' },
    { name: 'Namibia', translation: 'Namibie', code: 'na' },
    { name: 'Nauru', translation: 'Nauru', code: 'nr' },
    { name: 'Nepal', translation: 'Népal', code: 'np' },
    { name: 'Netherlands', translation: 'Pays-Bas', code: 'nl' },
    { name: 'New Caledonia', translation: 'Nouvelle Calédonie', code: 'nc' },
    { name: 'New Guinea', translation: 'Nouvelle Guinée', code: 'pg' },
    { name: 'New Zealand', translation: 'Nouvelle-Zélande', code: 'nz' },
    { name: 'Nicaragua', translation: 'Nicaragua', code: 'ni' },
    { name: 'Niger', translation: 'Niger', code: 'ne' },
    { name: 'Nigeria', translation: 'Nigeria', code: 'ng' },
    { name: 'Norway', translation: 'Norvège', code: 'no' },
    { name: 'Oman', translation: 'Oman', code: 'om' },
    { name: 'Pakistan', translation: 'Pakistan', code: 'pk' },
    { name: 'Palau', translation: 'Palaos', code: 'pw' },
    { name: 'Palestine', translation: 'Palestine', code: 'ps' },
    { name: 'Panama', translation: 'Panama', code: 'pa' },
    { name: 'Paraguay', translation: 'Paraguay', code: 'py' },
    { name: 'Peru', translation: 'Pérou', code: 'pe' },
    { name: 'Philippines', translation: 'Philippines', code: 'ph' },
    { name: 'Poland', translation: 'Pologne', code: 'pl' },
    { name: 'Portugal', translation: 'Portugal', code: 'pt' },
    { name: 'Puerto Rico', translation: 'Porto Rico', code: 'pr' },
    { name: 'Qatar', translation: 'Qatar', code: 'qa' },
    { name: 'Reunion', translation: 'Réunion', code: 're' },
    { name: 'Romania', translation: 'Roumanie', code: 'ro' },
    { name: 'Russia', translation: 'Russie', code: 'ru' },
    { name: 'Rwanda', translation: 'Rwanda', code: 'rw' },
    { name: 'Saint Helena', translation: 'Sainte Hélène', code: 'sh' },
    { name: 'Saint Lucia', translation: 'Sainte-Lucie', code: 'lc' },
    { name: 'Saint Pierre', translation: 'Saint Pierre', code: 'pm' },
    { name: 'Saint Vincent', translation: 'Saint Vincent', code: 'vc' },
    { name: 'Samoa', translation: 'Samoa', code: 'ws' },
    { name: 'San Marino', translation: 'Saint Marin', code: 'sm' },
    { name: 'Saudi Arabia', translation: 'Arabie Saoudite', code: 'sa' },
    { name: 'Scotland', translation: 'Ecosse', code: 'gb' },
    { name: 'Senegal', translation: 'Sénégal', code: 'sn' },
    { name: 'Serbia', translation: 'Serbie', code: 'cs' },
    { name: 'Seychelles', translation: 'Seychelles', code: 'sc' },
    { name: 'Sierra Leone', translation: 'Sierra Leone', code: 'sl' },
    { name: 'Singapore', translation: 'Singapour', code: 'sg' },
    { name: 'Slovakia', translation: 'Slovaquie', code: 'sk' },
    { name: 'Slovenia', translation: 'Slovénie', code: 'si' },
    { name: 'Solomon Islands', translation: 'Iles Salomon', code: 'sb' },
    { name: 'Somalia', translation: 'Somalie', code: 'so' },
    { name: 'South Africa', translation: 'Afrique du Sud', code: 'za' },
    { name: 'South Kore', translation: 'Corée du Sud', code: 'kr' },
    { name: 'Spain', translation: 'Espagne', code: 'es' },
    { name: 'Sri Lanka', translation: 'Sri Lanka', code: 'lk' },
    { name: 'Sudan', translation: 'Soudan', code: 'sd' },
    { name: 'Suriname', translation: 'Suriname', code: 'sr' },
    { name: 'Swaziland', translation: 'Swaziland', code: 'sz' },
    { name: 'Sweden', translation: 'Suède', code: 'se' },
    { name: 'Switzerland', translation: 'Suisse', code: 'ch' },
    { name: 'Syria', translation: 'Syrie', code: 'sy' },
    { name: 'Taiwan', translation: 'Taïwan', code: 'tw' },
    { name: 'Tajikistan', translation: 'Tadjikistan', code: 'tj' },
    { name: 'Tanzania', translation: 'Tanzanie', code: 'tz' },
    { name: 'Thailand', translation: 'Thaïlande', code: 'th' },
    { name: 'Timorleste', translation: 'Timorleste', code: 'tl' },
    { name: 'Togo', translation: 'Togo', code: 'tg' },
    { name: 'Tokelau', translation: 'Tokélaou', code: 'tk' },
    { name: 'Tonga', translation: 'Tonga', code: 'to' },
    { name: 'Trinidad', translation: 'Trinidad', code: 'tt' },
    { name: 'Tunisia', translation: 'Tunisie', code: 'tn' },
    { name: 'Turkey', translation: 'Turquie', code: 'tr' },
    { name: 'Turkmenistan', translation: 'Turkménistan', code: 'tm' },
    { name: 'Tuvalu', translation: 'Tuvalu', code: 'tv' },
    { name: 'United Arab Emirates', translation: 'Emirats Arabes Unis', code: 'ae' },
    { name: 'Uganda', translation: 'Ouganda', code: 'ug' },
    { name: 'Ukraine', translation: 'Ukraine', code: 'ua' },
    { name: 'United States', translation: 'Etats Unis', code: 'us' },
    { name: 'Uruguay', translation: 'Uruguay', code: 'uy' },
    { name: 'Uzbekistan', translation: 'Ouzbekistan', code: 'uz' },
    { name: 'Vanuatu', translation: 'Vanuatu', code: 'vu' },
    { name: 'Venezuela', translation: 'Venezuela', code: 've' },
    { name: 'Vietnam', translation: 'Vietnam', code: 'vn' },
    { name: 'Wales', translation: 'Pays de Galles', code: 'gb' },
    { name: 'Wallis And Futuna', translation: 'Wallis Et Futuna', code: 'wf' },
    { name: 'Western Sahara', translation: 'Sahara occidental', code: 'eh' },
    { name: 'Yemen', translation: 'Yémen', code: 'ye' },
    { name: 'Zambia', translation: 'Zambia', code: 'zm' },
    { name: 'Zimbabwe', translation: 'Zimbabwe', code: 'zw' },
  ];

  transform(value: any, args?: any): any {
    if (value) {
      return CountryCodePipe.countries.find(country => country.translation.toLowerCase() === value.toLowerCase()).code;
    }

    return null;
  }

}

export function countries() {
  return CountryCodePipe.countries.sort((c1, c2) => {
    if (c1.translation < c2.translation) { return -1; }
    if (c1.translation > c2.translation) { return 1; }
    return 0;
  });
}
