name: Test docker build

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!staging"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  back-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Show Dockerfile content used
      run: cat back/Dockerfile.production

    - name: Build back prod
      uses: docker/build-push-action@v3
      with:
        context: back
        file: back/Dockerfile.production
        push: false
        tags: numerisisep/back:prod
        cache-from: type=gha
        cache-to: type=gha

  front-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build front prod
      uses: docker/build-push-action@v3
      with:
        context: front
        file: front/Dockerfile.production
        push: false
        tags: numerisisep/front:prod
        cache-from: type=gha
        cache-to: type=gha

  back-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build back dev
      uses: docker/build-push-action@v3
      with:
        context: back
        file: back/Dockerfile
        push: false
        tags: numerisisep/back:dev
        cache-from: type=gha
        cache-to: type=gha

  front-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build front dev
      uses: docker/build-push-action@v3
      with:
        context: front
        file: front/Dockerfile
        push: false
        tags: numerisisep/front:dev
        cache-from: type=gha
        cache-to: type=gha
